import fs from "fs";
import path from "path";
import hre from "hardhat";

// Safe Transaction Builder app version stamped into the batch meta (informational; the import doesn't enforce it).
const TX_BUILDER_VERSION = "1.16.5";

// Safe TX Builder `inputs` for a function, read from the contract ABI.
// Primitive params and primitive arrays only; throws on struct/tuple params,
// where ethers v5 drops internalType + components so Safe gets an undecodable row.
// Struct-typed functions must build inputs from the artifact ABI.
export function inputsOf(contract: any, fnName: string) {
  return contract.interface.getFunction(fnName).inputs.map((p: any) => {
    if (p.components) {
      throw new Error(`inputsOf(${fnName}): struct param "${p.name}" unsupported; source inputs from the artifact ABI`);
    }
    return { name: p.name, type: p.type, internalType: p.type };
  });
}

// Write `transactions` as a Safe Transaction Builder batch to
// out/safe-batch-<scriptName>-<label>-<network>-<stamp>.json (no-op when empty).
// scriptName and optional label drive the filename and meta name.
// Optional name/description override the generated meta (e.g. to embed a source tx hash).
export function writeSafeBatchJson({
  scriptName,
  label,
  transactions,
  createdFromSafeAddress = "",
  name,
  description,
}: {
  scriptName: string;
  label?: string;
  transactions: any[];
  createdFromSafeAddress?: string;
  name?: string;
  description?: string;
}) {
  if (transactions.length === 0) return;

  const outDir = "out";
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const slug = label ? `${scriptName}-${label}` : scriptName;
  const title = label ? `${scriptName} ${label}` : scriptName;
  const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const filename = path.join(outDir, `safe-batch-${slug}-${hre.network.name}-${stamp}.json`);

  const batch = {
    version: "1.0",
    chainId: String(hre.network.config.chainId),
    createdAt: Date.now(),
    meta: {
      name: name ?? `${title} (${transactions.length} txs)`,
      description: description ?? `Generated by scripts/${scriptName}.ts on ${hre.network.name}`,
      txBuilderVersion: TX_BUILDER_VERSION,
      createdFromSafeAddress,
      createdFromOwnerAddress: "",
      checksum: "",
    },
    transactions,
  };

  fs.writeFileSync(filename, JSON.stringify(batch, null, 2));
  console.log(`\nSafe batch written: ${filename}`);
  console.log(`  Load via Safe --> Transaction Builder --> "Drag and drop JSON file"`);
}
