#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint
git add $(git diff --name-only --cached --diff-filter=AM)

# Update deployment documentation if deployment files changed
./scripts/generateDeploymentDocs.sh
